### ISSUE TITLE
Current event is not a tag push. Current event will be skipped.

### ISSUE THREAD

**Issue by ar-cyber** [xresloader/upload-to-github-release-test#1]
Whenever i run the workflow:
Current event is not a tag push.
Current event will be skipped.

how to fix?

**Comment by owent** [comment]
What's your configure?

**Comment by ar-cyber** [comment]
> What's your configure?

wdym?

**Comment by ar-cyber** [comment]
Oh I fixed this by setting the `tag` option to `false`. This fixed the issue.
